/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasAkhir;

import javax.swing.JOptionPane;
import tugasAkhir.HomeFrame;

/**
 *
 * @author user
 */
public class SplashScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SplashScreen.class.getName());

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackGround = new javax.swing.JPanel();
        LoadingLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();
        imgBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 500));
        setUndecorated(true);

        pnlBackGround.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackGround.setPreferredSize(new java.awt.Dimension(900, 500));
        pnlBackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoadingLabel.setBackground(new java.awt.Color(255, 255, 255));
        LoadingLabel.setForeground(new java.awt.Color(0, 51, 102));
        LoadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoadingLabel.setText("Loading...");
        pnlBackGround.add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Prayer Reminder");
        pnlBackGround.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 190, -1));

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -");
        pnlBackGround.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        LoadingValue.setForeground(new java.awt.Color(0, 51, 102));
        LoadingValue.setText("0%");
        pnlBackGround.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, -1, -1));

        LoadingBar.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackGround.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 570, 20));

        imgBackGround.setBackground(new java.awt.Color(153, 255, 255));
        imgBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background6.jpg"))); // NOI18N
        pnlBackGround.add(imgBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));
        imgBackGround.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        SplashScreen sp = new SplashScreen();
        sp.setVisible(true);
        
        new Thread(() -> {
            try{
                for (int i = 0; i <= 100; i++) {// for modul 2
                    Thread.sleep(100);
                    sp.LoadingValue.setText(i + "%");

                    if(i == 0){
                        sp.LoadingLabel.setText("Sabar dulu, ya...");
                    }
                    if(i == 20){
                        sp.LoadingLabel.setText("Mempersiapkan data...");
                    }
                    if(i == 50){
                        sp.LoadingLabel.setText("Mencari yang terbaik...");
                    }
                    if(i == 70){
                        sp.LoadingLabel.setText("Sedikit lagi selesai");
                    }
                    if(i == 90){
                        sp.LoadingLabel.setText("Hampir tiba!");
                    }
                    if(i == 100){
                        sp.LoadingLabel.setText("Alhamdulillah, Berhasil!");
                    }
                    sp.LoadingBar.setValue(i);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            sp.dispose();
            new HomeFrame().setVisible(true);
        }).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel imgBackGround;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlBackGround;
    // End of variables declaration//GEN-END:variables
}
